
package com.test;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-07T00:50:53.044+08:00
 * Generated source version: 3.3.7
 *
 */
public final class StaffWebServiceSoap_StaffWebServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "StaffWebService");

    private StaffWebServiceSoap_StaffWebServiceSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = StaffWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        StaffWebService ss = new StaffWebService(wsdlURL, SERVICE_NAME);

        StaffWebServiceSoap port = ss.getStaffWebServiceSoap();

        {
        System.out.println("Invoking setWorkerInfo...");
        WorkerInfo _setWorkerInfo_workerInfo = null;
        ProcessedResultsOfString _setWorkerInfo__return = port.setWorkerInfo(_setWorkerInfo_workerInfo);
        System.out.println("setWorkerInfo.result=" + _setWorkerInfo__return);


        }
        {
        System.out.println("Invoking uploadCardRecord...");
        CardRecord _uploadCardRecord_cardRecord = null;
        ProcessedResultsOfString _uploadCardRecord__return = port.uploadCardRecord(_uploadCardRecord_cardRecord);
        System.out.println("uploadCardRecord.result=" + _uploadCardRecord__return);


        }
        {
        System.out.println("Invoking uploadLocationInfo...");
        LocationInfo _uploadLocationInfo_locationInfo = null;
        ProcessedResultsOfString _uploadLocationInfo__return = port.uploadLocationInfo(_uploadLocationInfo_locationInfo);
        System.out.println("uploadLocationInfo.result=" + _uploadLocationInfo__return);


        }

        System.exit(0);
    }

}
