package com.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-07T00:50:53.054+08:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "StaffWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface StaffWebServiceSoap {

    /**
     * 人员信息录入接口。
     */
    @WebMethod(operationName = "SetWorkerInfo", action = "http://tempuri.org/SetWorkerInfo")
    @RequestWrapper(localName = "SetWorkerInfo", targetNamespace = "http://tempuri.org/", className = "com.test.SetWorkerInfo")
    @ResponseWrapper(localName = "SetWorkerInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.test.SetWorkerInfoResponse")
    @WebResult(name = "SetWorkerInfoResult", targetNamespace = "http://tempuri.org/")
    public ProcessedResultsOfString setWorkerInfo(

        @WebParam(name = "workerInfo", targetNamespace = "http://tempuri.org/")
        WorkerInfo workerInfo
    );

    /**
     * 上传工人考勤信息。
     */
    @WebMethod(operationName = "UploadCardRecord", action = "http://tempuri.org/UploadCardRecord")
    @RequestWrapper(localName = "UploadCardRecord", targetNamespace = "http://tempuri.org/", className = "com.test.UploadCardRecord")
    @ResponseWrapper(localName = "UploadCardRecordResponse", targetNamespace = "http://tempuri.org/", className = "com.test.UploadCardRecordResponse")
    @WebResult(name = "UploadCardRecordResult", targetNamespace = "http://tempuri.org/")
    public ProcessedResultsOfString uploadCardRecord(

        @WebParam(name = "cardRecord", targetNamespace = "http://tempuri.org/")
        CardRecord cardRecord
    );

    /**
     * 上传定位信息接口。
     */
    @WebMethod(operationName = "UploadLocationInfo", action = "http://tempuri.org/UploadLocationInfo")
    @RequestWrapper(localName = "UploadLocationInfo", targetNamespace = "http://tempuri.org/", className = "com.test.UploadLocationInfo")
    @ResponseWrapper(localName = "UploadLocationInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.test.UploadLocationInfoResponse")
    @WebResult(name = "UploadLocationInfoResult", targetNamespace = "http://tempuri.org/")
    public ProcessedResultsOfString uploadLocationInfo(

        @WebParam(name = "locationInfo", targetNamespace = "http://tempuri.org/")
        LocationInfo locationInfo
    );
}
